package a.validate.trycatch_throw;

public class Ex03BasicDemo_Throw_Throws {
  public static void main(String[] args) {
	/**
	 * validation : validate trước doạn code bị exceptoptry 
	 * try catch đưa đoạn code có khả năng bị exception vào khôi try
	 */
	  
	  
	  System.out.println(" demo throw throws \n");
	  System.out.println("divide(8,2)-->" + divide(8,2) + "\n");
	 
	  
		  
	 
	  	  
	  	  
}
  
  
  private static int divide(int a, int b) {
	  return a / b;
  }
}
